version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "romanlaptev"
      POSTGRES_PASSWORD: "1111"
    volumes:
      - pgdatavolume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
      pgdatavolume:
        external: true